# Generated by Django 4.0.2 on 2022-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='articles')),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procode', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
                ('added_on', models.DateTimeField()),
            ],
        ),
    ]
